name: Mutation testing

on: workflow_dispatch

jobs:
  mutation-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.12
      - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ secrets.CACHE_SEED }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('./poetry.lock') }}
          restore-keys: ${{ runner.os }}-pip-${{ secrets.CACHE_SEED }}-${{ env.PYTHON_VERSION }}-
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install Poetry
        run: pip install poetry
      - name: Install Python dependencies
        run: poetry install
      - name: Run mutation tests
        run: poetry run mutmut run --no-progress --runner="pytest --assert=plain --exitfirst"
      - name: Create mutation test report
        run: poetry run mutmut junitxml > mutmut.xml
        if: ${{ failure() }}
      - name: Archive mutation test report
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: mutation-test-report
          path: mutmut.xml
        if: ${{ failure() }}
